<?php
session_start();
header("Content-Type: application/json");	
	
include '../../../config.php';
include '../opendb.php';
include '../funciones.php';

$current = $_REQUEST["current"];
$rowcount = $_REQUEST["rowCount"];
$search = $_REQUEST["searchPhrase"];

$sql = "SELECT CR.ID_REGISTRO AS id, 
		IFNULL(UPPER(CH.HOSPITAL), '') AS sHospital, 
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 1 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sProveniencia,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 7 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sAnoDiagnostico,
		IFNULL(UPPER(CR.CRNUMERO_REGISTRO), '') AS sNumeroRegistro, 
		IFNULL(UPPER(CR.CRAPELLIDO_PATERNO), '') AS sApellidoPaterno,
		IFNULL(UPPER(CR.CRAPELLIDO_MATERNO), '') AS sApellidoMaterno,
		IFNULL(UPPER(CR.CRNOMBRE), '') AS sNombre,
		IFNULL(CR.CRFECHA_NACIMIENTO ,'') AS sFechaNacimiento,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 2 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEscolaridad,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 10 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEscolaridadAnos,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 3 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sOcupacion,
		IFNULL(CASE CR.CRTABAQUISMO WHEN 1 THEN 'NO' WHEN 2 THEN 'SI' ELSE CR.CRTABAQUISMO END, '') AS sTabaquismo,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 8 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sAnosTabaquismo,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 9 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sCantidadCigarros,
		IFNULL(CASE CR.CRHISTORIAL_FAMILIAR WHEN 1 THEN 'NO' WHEN 2 THEN 'SI' ELSE CR.CRHISTORIAL_FAMILIAR END, '') AS sHistoriaFamiliar,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 4 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTipoCancer,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 5 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sOtrosTiposCancer,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 6 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sGradoFamiliar,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sModalidadDiagostico,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 12 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sSintomas,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			(SELECT CR_FECHA_BIOPSIA  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			(SELECT CR_NIVEL_APE  FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			(SELECT CDR_date_RTUP  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			(SELECT CR_FECHA_BIOPSIA  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			(SELECT CR_FECHA_BIOPSIA  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sFechaRegistro,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			(SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 13	 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			(SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 76 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 3 THEN
			(SELECT C_RTUP  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			''
		WHEN 5 THEN
			(SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 13 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		END, '')
		AS sNumeroCilindros,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			(SELECT CR_OTROCILINDRO  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			''
		WHEN 3 THEN
			''
		WHEN 4 THEN
			''
		WHEN 5 THEN
			(SELECT CR_OTROCILINDRO FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sNumeroCilindrosOtro,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 70 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 70 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 70 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 70 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sRHP,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRORHP  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_OTRORHP  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_OTRORHP  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_OTRORHP  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sEspeficicarOtroCancer,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_GLEASON1  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_GLEASON1  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_GLEASON1  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_GLEASON1  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sGleason1,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_GLEASON2  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_GLEASON2  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_GLEASON2  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_GLEASON2  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sGleason2,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_GLEASON_DESCONOCIDO  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_GLEASON_DESCONOCIDO  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_GLEASON_DESCONOCIDO FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_GLEASON_DESCONOCIDO FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sGleasonDesconocido,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_GLEASONSUMA  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_GLEASONSUMA  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_GLEASONSUMA  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_GLEASONSUMA  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sGloasonSuma,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_APE_TOTAL  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_APE_TOTAL  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_APE_TOTAL  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_APE_TOTAL  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sApeDiagnosticoTotal,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_APE_LIBRE  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_APE_LIBRE  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_APE_LIBRE  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_APE_LIBRE  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sApeDiagnosticoLibre,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_DESCONOCIDO  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_DESCONOCIDO  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_DESCONOCIDO  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_DESCONOCIDO  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sApeDesconocido,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTROSMARCADORES  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_OTROSMARCADORES  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			''
		WHEN 5 THEN
			
			(SELECT CR_OTROSMARCADORES  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sApeOtrosMarcadores,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 14 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sIndiqueOtrosMarcadores,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRO_MARCADOR  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_OTRO_MARCADOR  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			''
		WHEN 5 THEN
			
			(SELECT CR_OTRO_MARCADOR  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sMarcadoresEspeficicar,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_ESTUDIOIMAGEN  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_ESTUDIOIMAGEN  FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_ESTUDIOIMAGEN  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_ESTUDIOIMAGEN  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_ESTUDIOIMAGEN  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sEstudiosImagen,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 71 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTAC,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 19 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sSeleccioneTac,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRO_TAC FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_OTRO_TAC FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_OTRO_TAC FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_OTRO_TAC FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_OTRO_TAC FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sEspecificarOtroTac,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 72 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sRMI,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 20 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sSeleccioneRMI,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRO_RMI  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_OTRO_RMI  FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_OTRO_RMI FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_OTRO_RMI FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_OTRO_RMI FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sEspecificarOtroRMI,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 73 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sPET,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 17 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sSeleccionePET,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRO_PET FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_OTRO_PET FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_OTRO_PET FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_OTRO_PET FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_OTRO_PET FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sEspecificarOtroPET,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 74 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sGGO,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRO_GGO FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_OTRO_GGO FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_OTRO_GGO FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_OTRO_GGO FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_OTRO_GGO FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sSeleccioneGGO,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_NUMERO_LESIONES FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_NUMERO_LESIONES FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_NUMERO_LESIONES FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_NUMERO_LESIONES FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_NUMERO_LESIONES FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sNumeroLesiones,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 75 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTR,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 15 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEtapificacionClinicaT,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 16 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEtapificacionClinicaN,
		IFNULL((SELECT UPPER(ETIQUETA_OPCION_CAMPO) FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 21 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEtapificacionClinicaM,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_VIGILANCIA_ACTIVA FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_VIGILANCIA_ACTIVA FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_VIGILANCIA_ACTIVA FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_VIGILANCIA_ACTIVA FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_VIGILANCIA_ACTIVA FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sVigilanciaActiva,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_DIFERIDO  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_DIFERIDO FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_DIFERIDO FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_DIFERIDO FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_DIFERIDO FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sTratamientoDiferido,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_PROGRESION_VIGILANCIA FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_PROGRESION_VIGILANCIA FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_PROGRESION_VIGILANCIA FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_PROGRESION_VIGILANCIA FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_PROGRESION_VIGILANCIA FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sProgresionPostVigActiva
	FROM C_REGISTROS AS CR
		INNER JOIN C_USUARIOS AS CU ON CU.ID_USUARIO = CR.CRUSUARIO_INICIO
		INNER JOIN C_HOSPITALES AS CH ON CU.CUHOSPITAL = CH.ID_HOSPITAL 
		ORDER BY CR.ID_REGISTRO DESC LIMIT 0, 100;";

$sqlcount = "SELECT COUNT(*) as cuenta
	FROM C_REGISTROS AS CR
		INNER JOIN C_USUARIOS AS CU ON CU.ID_USUARIO = CR.CRUSUARIO_INICIO
		INNER JOIN C_HOSPITALES AS CH ON CU.CUHOSPITAL = CH.ID_HOSPITAL
		ORDER BY CR.ID_REGISTRO DESC LIMIT 0, 300;";


$registros = mysqli_query($conexion,$sqlcount);
$error = mysqli_error($conexion);
$count = 0;
while($row = mysqli_fetch_assoc($registros)) {
	$count = $row["cuenta"];
}

$registros = mysqli_query($conexion,$sql);
$error = mysqli_error($conexion);


$rows = array();
while($row = mysqli_fetch_assoc($registros)) {
	$rows[] = $row;
}

$data = array(
	"current" 	=> (int)$current,
	"rowCount"	=> (int)$rowcount,
	"rows" => array($rows),
	"total" => $count
);

echo jsonformat($data);


include '../closedb.php';
?>