<?php 
session_start();
header('Content-Type: text/html; charset=utf-8');

/*
Mysql To Excel
Generación de excel versión 1.0
Nicolás Pardo - 2007
*/
#Conexion a la db
include '../../config.php';
include '../php/opendb.php';
include '../php/funciones.php';

#Sql, acá pone tu consulta a la tabla que necesites exportar filtrando los datos que creas necesarios.
$sql = "SELECT CR.ID_REGISTRO AS id, 
		IFNULL(CH.HOSPITAL, '') AS sHospital, 
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 1 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sProveniencia,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 7 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sAnoDiagnostico,
		IFNULL(CR.CRNUMERO_REGISTRO, '') AS sNumeroRegistro, 
		IFNULL(CR.CRAPELLIDO_PATERNO, '') AS sApellidoPaterno,
		IFNULL(CR.CRAPELLIDO_MATERNO, '') AS sApellidoMaterno,
		IFNULL(CR.CRNOMBRE, '') AS sNombre,
		IFNULL(CR.CRFECHA_NACIMIENTO ,'') AS sFechaNacimiento,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 2 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEscolaridad,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 10 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEscolaridadAnos,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 3 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sOcupacion,
		IFNULL(CASE CR.CRTABAQUISMO WHEN 1 THEN 'NO' WHEN 2 THEN 'SI' ELSE CR.CRTABAQUISMO END, '') AS sTabaquismo,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 8 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sAnosTabaquismo,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 9 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sCantidadCigarros,
		IFNULL(CASE CR.CRHISTORIAL_FAMILIAR WHEN 1 THEN 'NO' WHEN 2 THEN 'SI' ELSE CR.CRHISTORIAL_FAMILIAR END, '') AS sHistoriaFamiliar,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 4 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTipoCancer,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 5 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sOtrosTiposCancer,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 6 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sGradoFamiliar,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sModalidadDiagostico,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 12 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sSintomas,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			(SELECT CR_FECHA_BIOPSIA  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			(SELECT CR_NIVEL_APE  FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			(SELECT CDR_date_RTUP  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			(SELECT CR_FECHA_BIOPSIA  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			(SELECT CR_FECHA_BIOPSIA  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sFechaRegistro,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			(SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 13	 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			(SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 76 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 3 THEN
			(SELECT C_RTUP  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			''
		WHEN 5 THEN
			(SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 13 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		END, '')
		AS sNumeroCilindros,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			(SELECT CR_OTROCILINDRO  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			''
		WHEN 3 THEN
			''
		WHEN 4 THEN
			''
		WHEN 5 THEN
			(SELECT CR_OTROCILINDRO FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sNumeroCilindrosOtro,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 70 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 70 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 70 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 70 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sRHP,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRORHP  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_OTRORHP  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_OTRORHP  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_OTRORHP  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sEspeficicarOtroCancer,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_GLEASON1  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_GLEASON1  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_GLEASON1  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_GLEASON1  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sGleason1,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_GLEASON2  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_GLEASON2  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_GLEASON2  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_GLEASON2  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sGleason2,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_GLEASON_DESCONOCIDO  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_GLEASON_DESCONOCIDO  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_GLEASON_DESCONOCIDO FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_GLEASON_DESCONOCIDO FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sGleasonDesconocido,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_GLEASONSUMA  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_GLEASONSUMA  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_GLEASONSUMA  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_GLEASONSUMA  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sGloasonSuma,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_APE_TOTAL  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_APE_TOTAL  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_APE_TOTAL  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_APE_TOTAL  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sApeDiagnosticoTotal,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_APE_LIBRE  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_APE_LIBRE  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_APE_LIBRE  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_APE_LIBRE  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sApeDiagnosticoLibre,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_DESCONOCIDO  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_DESCONOCIDO  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_DESCONOCIDO  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_DESCONOCIDO  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sApeDesconocido,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTROSMARCADORES  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_OTROSMARCADORES  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			''
		WHEN 5 THEN
			
			(SELECT CR_OTROSMARCADORES  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sApeOtrosMarcadores,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 14 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sIndiqueOtrosMarcadores,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRO_MARCADOR  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			''
		WHEN 3 THEN
			
			(SELECT CR_OTRO_MARCADOR  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			''
		WHEN 5 THEN
			
			(SELECT CR_OTRO_MARCADOR  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sMarcadoresEspeficicar,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_ESTUDIOIMAGEN  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_ESTUDIOIMAGEN  FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_ESTUDIOIMAGEN  FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_ESTUDIOIMAGEN  FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_ESTUDIOIMAGEN  FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sEstudiosImagen,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 71 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTAC,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 19 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sSeleccioneTac,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRO_TAC FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_OTRO_TAC FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_OTRO_TAC FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_OTRO_TAC FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_OTRO_TAC FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sEspecificarOtroTac,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 72 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sRMI,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 20 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sSeleccioneRMI,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRO_RMI  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_OTRO_RMI  FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_OTRO_RMI FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_OTRO_RMI FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_OTRO_RMI FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sEspecificarOtroRMI,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 73 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sPET,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 17 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sSeleccionePET,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRO_PET FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_OTRO_PET FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_OTRO_PET FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_OTRO_PET FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_OTRO_PET FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sEspecificarOtroPET,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 74 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sGGO,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_OTRO_GGO FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_OTRO_GGO FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_OTRO_GGO FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_OTRO_GGO FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_OTRO_GGO FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sSeleccioneGGO,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_NUMERO_LESIONES FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_NUMERO_LESIONES FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_NUMERO_LESIONES FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_NUMERO_LESIONES FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_NUMERO_LESIONES FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sNumeroLesiones,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 75 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTR,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 15 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEtapificacionClinicaT,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 16 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEtapificacionClinicaN,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 21 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEtapificacionClinicaM,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_VIGILANCIA_ACTIVA FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_VIGILANCIA_ACTIVA FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_VIGILANCIA_ACTIVA FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_VIGILANCIA_ACTIVA FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_VIGILANCIA_ACTIVA FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sVigilanciaActiva,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_DIFERIDO  FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_DIFERIDO FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_DIFERIDO FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_DIFERIDO FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_DIFERIDO FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sTratamientoDiferido,
		IFNULL(CASE (SELECT ID_OPCION_CAMPO  FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 11 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1) 
		WHEN 1 THEN
			
			(SELECT CR_PROGRESION_VIGILANCIA FROM C_DIAG_BIOPSIA WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 2 THEN
			
			(SELECT CR_PROGRESION_VIGILANCIA FROM C_DIAG_CLINICO_APE WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 3 THEN
			
			(SELECT CR_PROGRESION_VIGILANCIA FROM C_DIAG_RTUP WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 4 THEN
			
			(SELECT CR_PROGRESION_VIGILANCIA FROM C_DIAG_BIOPSIA_OTRO_SITIO WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		WHEN 5 THEN
			
			(SELECT CR_PROGRESION_VIGILANCIA FROM C_DIAG_BIOPSIA_SATURACION WHERE ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1)
		END, '')
		AS sProgresionPostVigActiva,
		IFNULL((SELECT CR_DESCONOCIDO FROM C_DIAG_DESCONOCIDO WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sDesconocido,
		IFNULL((SELECT CRFECHA_CIRUGIA FROM C_CIRUGIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaCirugia,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 23 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sAbordaje,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 27 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sSangradoIntraOp,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 28 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sNoPaqueGlobulares,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 29 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sComplicacionesTramsop,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 32 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sComplicacionesTardias,
		'' AS sComplicacionesTardiasOtro,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 33 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sContinencia,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 34 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sPotencia,
		IFNULL((SELECT CRAE_POST_OPERATORIO FROM C_CIRUGIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sApePostOperatorio,
		IFNULL((SELECT CRAPE_DESCONOCIDO FROM C_CIRUGIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sApeDesconocidoCirugia,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 35 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sRadioterapiaAdyuvante,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 36 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sProgresionPostRadiot,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 37 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sBloqueoHormonalPostCir,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 43 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sBloqueoCual,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 40 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sRecurrenciaBioqui,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 44 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sRecurreTratamiento,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 42 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTipologiaRecurre,
		IFNULL((SELECT CRAPE_RECURRENCIA FROM C_CIRUGIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sApeRecurrencia,
		IFNULL((SELECT CRFECHA_RECURR_AD FROM C_CIRUGIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaRecurrencia,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 39 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sProgresPostCir,
		IFNULL((SELECT CRCOMENTARIOS FROM C_CIRUGIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sCirugiaComentarios,
		IFNULL((SELECT CRNUMERO_CONSULTAS FROM C_CIRUGIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sNoConsultas,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 46 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sBloqueoHormonal,
		IFNULL((SELECT CR_FECHAINICIO FROM C_RADIOTERAPIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaInicio,
		IFNULL((SELECT CR_FECHATERMINO FROM C_RADIOTERAPIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaTermino,
		IFNULL((SELECT CR_APE_POST_RT FROM C_RADIOTERAPIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sAPEnadirpost,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 48 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sComplicacionesTardiasRad,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 51 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTipoRecurrencia,
		IFNULL((SELECT CR_NUMERO_CONSULTAS FROM C_RADIOTERAPIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sNoTotalConsultas,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 49 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sRecurrenciaBioquimica,
		IFNULL((SELECT CR_APE_RECURR FROM C_RADIOTERAPIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sApeRecurrenciaRad,
		IFNULL((SELECT CR_RECURR_FECHA FROM C_RADIOTERAPIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaRecurrenciaRad,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 50 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sProgresionPostRadioterapia,
		IFNULL((SELECT CR_INICIO_PROG_FECHA FROM C_RADIOTERAPIA WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaInicioPrograsionPostRadio,
		IFNULL((SELECT CR_DATE_METASTASIS FROM C_METASTASIS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaInicioMeta,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 52 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sOrquiectomia,
		IFNULL((SELECT CRFECHA_ORQUITECT FROM C_METASTASIS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaOrquitectomia,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 53 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sAnalogoLHRH,
		IFNULL((SELECT CRFECHA_LHRH FROM C_METASTASIS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaAnalogoLHRh,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 54 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sAntagonstaLHRH,
		IFNULL((SELECT CRFECHAINICIO_ANTIANDROGENO FROM C_METASTASIS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sAntagonistaLHRH,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 55 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sAntiogeno,
		IFNULL((SELECT CRFECHAINICIO_ANTAG_LHRH FROM C_METASTASIS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaInicioAntiogeno,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 56 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sBloqueoHormonas,
		IFNULL((SELECT CRAPE_NADIR_POSTBLOQUEO FROM C_METASTASIS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sApeNaDirBloqHormonal,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 57 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sQuimioterapia,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 58 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sHospitalQuimio,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 59 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sToxicidadQuimio,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 60 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTratamientoOsea,
		IFNULL((SELECT CRNUMERO_CONSULTAS FROM C_METASTASIS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sNumeroConsultasQuimio,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 61 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sResistenciaCastracion,
		IFNULL((SELECT CRFECHA_INICIO_RESIST FROM C_PROGRESION WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaInicioResCastra,
		IFNULL((SELECT CRNIVEL_TESTOSTERONA FROM C_PROGRESION WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sNivelTestosterona,
		IFNULL((SELECT CRNIVEL_APE FROM C_PROGRESION WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sNivelAPEProgresion,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 62 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEstudiosImagenProgresio,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 63 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS eEstudiosImagenCual,
		IFNULL((SELECT CROTRO_ESTUDIO_IMAGEN FROM C_PROGRESION WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sEstudiosImagenOtro,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 64 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTrataminetoSegLinea,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 65 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sTratamientoSegLineaCual,
		IFNULL((SELECT CROTRO_TRAT_SEGUNDA FROM C_PROGRESION WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sOtroTratSeg,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 66 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sQuimio,
		IFNULL((SELECT CRFECHA_INICIO_QUIMIO FROM C_PROGRESION WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaInicioQuimio,
		IFNULL((SELECT CRNUMERO_CONSULTAS FROM C_PROGRESION WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sNumeroConsultasProgresion,
		IFNULL((SELECT CRFECHA_ULTIMA_CONSULTA FROM C_ESTATUS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sEstatusFechaUltimaCons,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 67 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sEstatusUltimaCons,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 68 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sMuerteCancer,
		IFNULL((SELECT ETIQUETA_OPCION_CAMPO FROM C_RELACION_REGISTROS WHERE ID_TIPO_CAMPO = 69 AND ID_REGISTRO = CR.ID_REGISTRO LIMIT 0, 1), '') AS sMuerteOtraCausa,
		IFNULL((SELECT CR_CUALMUERTE FROM C_ESTATUS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sMuerteOtraCual,
		IFNULL((SELECT CR_FECHAMUERTE FROM C_ESTATUS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sFechaMuerteCancer,
		IFNULL((SELECT CR_OBSERVACIONES FROM C_ESTATUS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sObservaciones,
		IFNULL((SELECT CR_CERRADO FROM C_ESTATUS WHERE ID_REGISTRO = CR.ID_REGISTRO), '') AS  sCasoCerrado,
		CONCAT(CU.CUUSUARIO, ' ', CU.CUAPELLIDOS) AS Medico,
		CR.CRFECHA_INICIO AS FechaInicio
	FROM C_REGISTROS AS CR
		INNER JOIN C_USUARIOS AS CU ON CU.ID_USUARIO = CR.CRUSUARIO_INICIO
		INNER JOIN C_HOSPITALES AS CH ON CU.CUHOSPITAL = CH.ID_HOSPITAL ";

	if ($_SESSION["TIPO"] == 2) { 
		$sql = $sql . " WHERE CU.ID_USUARIO = {$_SESSION["ID_USUARIO"]}";
	}

	$sql = $sql . " ORDER BY CR.ID_REGISTRO DESC;";

$return = '';
$resultado = mysqli_query($conexion, $sql);
$registros = mysqli_num_rows($resultado);

if($registros>0){
    $return .= '<table border=1>';
    $cols = 0;
    while($rs = mysqli_fetch_assoc($resultado)){
        $return .= '<tr>';
        if($cols==0){
            $cols = 130;
            $cols_names = array();
			$cols_names[0] = "id";
			$cols_names[1] = "Hospital";
			$cols_names[2] = "Medico";
			$cols_names[3] = "Fecha Registro";
			$cols_names[4] = "Proveniencia";
			$cols_names[5] = "Año de Diagnostico";
			$cols_names[6] = "Número de registro";
			$cols_names[7] = "Apellido Paterno";
			$cols_names[8] = "Apellido Materno";
			$cols_names[9] = "Nombre(s)";
			$cols_names[10] = "Fecha de nacimiento";
			$cols_names[11] = "Escolaridad";
			$cols_names[12] = "Escolaridad en años";
			$cols_names[13] = "Ocupación";
			$cols_names[14] = "Tabaquismo";
			$cols_names[15] = "Años de tabaquismo";
			$cols_names[16] = "Cantidad (cigarros al día)";
			$cols_names[17] = "Historia Familiar de Cáncer";
			$cols_names[18] = "Tipo de cáncer";
			$cols_names[19] = "Otros tipos de Cáncer";
			$cols_names[20] = "Grado del familiar con Cáncer";
			$cols_names[21] = "Modalidad del diagnóstico";
			$cols_names[22] = "Síntomas";
			$cols_names[23] = "Fecha de Biopsia, Nivel actual de APE, Fecha de RTUP";
			$cols_names[24] = "Número de Cilindros por Biopsia, Tacto Rectal, RTUP / Adenomectomía";
			$cols_names[25] = "Especificar otro";
			$cols_names[26] = "RHP Cáncer de Próstata";
			$cols_names[27] = "Especificar otro";
			$cols_names[28] = "Gleason1";
			$cols_names[29] = "Gleason2";
			$cols_names[30] = "Suma Gleason";
			$cols_names[31] = "Desconocido";
			$cols_names[32] = "APE al diagnóstico Total";
			$cols_names[33] = "APE al diagnóstico Libre";
			$cols_names[34] = "Desconocido";
			$cols_names[35] = "Otros Marcadores";
			$cols_names[36] = "Indique Otros Marcadores";
			$cols_names[37] = "Especificar otro";
			$cols_names[38] = "Estudios de Imagen";
			$cols_names[39] = "TAC";
			$cols_names[40] = "Seleccione TAC";
			$cols_names[41] = "Especificar otro";
			$cols_names[42] = "RMI";
			$cols_names[43] = "Seleccione RMI";
			$cols_names[44] = "Especificar otro";
			$cols_names[45] = "PET";
			$cols_names[46] = "Seleccione PET";
			$cols_names[47] = "Especificar otro";
			$cols_names[48] = "GGO";
			$cols_names[49] = "Seleccione GGO";
			$cols_names[50] = "Número de lesiones";
			$cols_names[51] = "TR";
			$cols_names[52] = "Etapificación Clínica T";
			$cols_names[53] = "Etapificación Clínica N";
			$cols_names[54] = "Etapificación Clínica M";
			$cols_names[55] = "Vigilancia Activa";
			$cols_names[56] = "Tratamiento Diferido";
			$cols_names[57] = "Progresión post-vigilancia activa";
			$cols_names[58] = "Desconocido";
			$cols_names[59] = "Fecha Cirugia";
			$cols_names[60] = "Abordaje";
			$cols_names[61] = "Sangrado Estimado Intra-operatorio";
			$cols_names[62] = "Número de Paquetes Globulares Transfundidos";
			$cols_names[63] = "Complicaciones Transoperatorias";
			$cols_names[64] = "Complicaciones Tardías";
			$cols_names[65] = "Especificar otro";
			$cols_names[66] = "Continencia (a un año)";
			$cols_names[67] = "Potencia (a un año)";
			$cols_names[68] = "APE Post-Operatorio (Desde 6 semanas hasta 3 meses)";
			$cols_names[69] = "APE Desconocido";
			$cols_names[70] = "Radioterapia Adyuvante";
			$cols_names[71] = "Progresión Post-Radioterapia";
			$cols_names[72] = "Bloqueo Hormonal Post-Cirugía";
			$cols_names[73] = "Cuál";
			$cols_names[74] = "Recurrencia bioquímica";
			$cols_names[75] = "Tratamiento";
			$cols_names[76] = "Tipología de recurrencia";
			$cols_names[77] = "APE de recurrencia";
			$cols_names[78] = "Fecha recurrencia";
			$cols_names[79] = "Progresión Post-Cirugía";
			$cols_names[80] = "Comentarios";
			$cols_names[81] = "Número total de consultas";
			$cols_names[82] = "Bloqueo hormonal";
			$cols_names[83] = "Fecha de inicio";
			$cols_names[84] = "Fecha de termino";
			$cols_names[85] = "APE nadir Post-RT (considerando 6 meses, posterior al Tx)";
			$cols_names[86] = "Complicaciones tardías (dentro de 6 meses)";
			$cols_names[87] = "Tipo de recurrencia";
			$cols_names[88] = "Número total de consultas";
			$cols_names[89] = "Recurrencia bioquímica";
			$cols_names[90] = "APE de recurrencia";
			$cols_names[91] = "Fecha de recurrencia";
			$cols_names[92] = "Progresión Post-Radioterapia";
			$cols_names[93] = "Fecha de inicio de progresión Post-Radioterapia";
			$cols_names[94] = "Fecha de Inicio";
			$cols_names[95] = "Orquiectomía";
			$cols_names[96] = "Fecha de Orquitectomía";
			$cols_names[97] = "Análogo LHRH";
			$cols_names[98] = "Fecha de inicio Análogo LHRH";
			$cols_names[99] = "Antagonista LHRH";
			$cols_names[100] = "Fecha de inicio Antagonista LHRH";
			$cols_names[101] = "Anti andrógeno";
			$cols_names[102] = "Fecha de inicio Anti andrógeno";
			$cols_names[103] = "Bloqueo Hormonal Combinado (Se considera agonista LHRH más antiandrogénico o castración quirúrgica más antiandrogénico)";
			$cols_names[104] = "APE nadir post-Bloqueo Hormonal";
			$cols_names[105] = "Quimioterapia";
			$cols_names[106] = "Hospitalización por quimioterapia";
			$cols_names[107] = "Toxicidad por quimioterapia";
			$cols_names[108] = "Tratamiento salud ósea";
			$cols_names[109] = "Número de consultas durante quimioterapia";
			$cols_names[110] = "Resistencia a la Castración";
			$cols_names[111] = "Fecha de inicio de Resistencia a la Castración ";
			$cols_names[112] = "Nivel de Testosterona";
			$cols_names[113] = "Nivel de APE";
			$cols_names[114] = "Estudio de imagen";
			$cols_names[115] = "Cuál";
			$cols_names[116] = "Especificar otro";
			$cols_names[117] = "Tratamiento de segunda línea";
			$cols_names[118] = "Cuál";
			$cols_names[119] = "Especificar otro";
			$cols_names[120] = "Quimioterapia ";
			$cols_names[121] = "Fecha de inicio Quimioterapia";
			$cols_names[122] = "Número de consultas";
			$cols_names[123] = "Fecha de la última consulta";
			$cols_names[124] = "Estatus de última consulta";
			$cols_names[125] = "Muerte por cáncer";
			$cols_names[126] = "Muerte por otra causa";
			$cols_names[127] = "Cual";
			$cols_names[128] = "Fecha de muerte por cáncer";
			$cols_names[129] = "Observaciones";
			$cols_names[130] = "Caso cerrado por fallecimiento o abandono de tratamiento";
			
	
			
            for($i=0; $i<130; $i++){
                $return .= '<th>'.$cols_names[$i].'</th>';                
            }
            $return .= '</tr><tr>';
        }
			$return .= '<td>'.html_entity_decode($rs['id']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sHospital']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['Medico']).'</td>';	
			$return .= '<td>'.html_entity_decode($rs['FechaInicio']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sProveniencia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sAnoDiagnostico']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNumeroRegistro']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApellidoPaterno']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApellidoMaterno']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNombre']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaNacimiento']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEscolaridad']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEscolaridadAnos']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sOcupacion']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sTabaquismo']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sAnosTabaquismo']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sCantidadCigarros']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sHistoriaFamiliar']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sTipoCancer']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sOtrosTiposCancer']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sGradoFamiliar']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sModalidadDiagostico']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sSintomas']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaRegistro']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNumeroCilindros']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNumeroCilindrosOtro']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sRHP']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEspeficicarOtroCancer']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sGleason1']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sGleason2']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sGleasonDesconocido']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sGloasonSuma']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApeDiagnosticoTotal']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApeDiagnosticoLibre']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApeDesconocido']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApeOtrosMarcadores']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sIndiqueOtrosMarcadores']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sMarcadoresEspeficicar']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEstudiosImagen']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sTAC']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sSeleccioneTac']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEspecificarOtroTac']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sRMI']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sSeleccioneRMI']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEspecificarOtroRMI']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sPET']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sSeleccionePET']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEspecificarOtroPET']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sGGO']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sSeleccioneGGO']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNumeroLesiones']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sTR']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEtapificacionClinicaT']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEtapificacionClinicaN']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEtapificacionClinicaM']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sVigilanciaActiva']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sTratamientoDiferido']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sProgresionPostVigActiva']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sDesconocido']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaCirugia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sAbordaje']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sSangradoIntraOp']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNoPaqueGlobulares']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sComplicacionesTramsop']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sComplicacionesTardias']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sComplicacionesTardiasOtro']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sContinencia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sPotencia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApePostOperatorio']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApeDesconocidoCirugia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sRadioterapiaAdyuvante']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sProgresionPostRadiot']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sBloqueoHormonalPostCir']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sBloqueoCual']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sRecurrenciaBioqui']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sRecurreTratamiento']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sTipologiaRecurre']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApeRecurrencia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaRecurrencia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sProgresPostCir']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sCirugiaComentarios']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNoConsultas']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sBloqueoHormonal']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaInicio']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaTermino']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sAPEnadirpost']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sComplicacionesTardiasRad']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sTipoRecurrencia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNoTotalConsultas']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sRecurrenciaBioquimica']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApeRecurrenciaRad']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaRecurrenciaRad']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sProgresionPostRadioterapia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaInicioPrograsionPostRadio']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaInicioMeta']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sOrquiectomia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaOrquitectomia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sAnalogoLHRH']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaAnalogoLHRh']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sAntagonstaLHRH']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sAntagonistaLHRH']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sAntiogeno']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaInicioAntiogeno']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sBloqueoHormonas']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sApeNaDirBloqHormonal']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sQuimioterapia']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sHospitalQuimio']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sToxicidadQuimio']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sTratamientoOsea']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNumeroConsultasQuimio']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sResistenciaCastracion']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaInicioResCastra']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNivelTestosterona']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNivelAPEProgresion']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEstudiosImagenProgresio']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['eEstudiosImagenCual']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEstudiosImagenOtro']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sTrataminetoSegLinea']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sTratamientoSegLineaCual']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sOtroTratSeg']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sQuimio']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaInicioQuimio']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sNumeroConsultasProgresion']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEstatusFechaUltimaCons']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sEstatusUltimaCons']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sMuerteCancer']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sMuerteOtraCausa']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sMuerteOtraCual']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sFechaMuerteCancer']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sObservaciones']).'</td>';
			$return .= '<td>'.html_entity_decode($rs['sCasoCerrado']).'</td>';
        
        $return .= '</tr>';
    }
    $return .= '</table>';
    mysqli_free_result($resultado);
}
#Cambiando el content-type más las <table> se pueden exportar formatos como csv
header("Content-type: application/vnd-ms-excel; charset=iso-8859-1");
header("Content-Disposition: attachment; filename=Reporte_".date('d-m-Y').".xls");
echo $return;
exit;

?>